### ISSUE TITLE
Link the Table of Contents to all the parts in the repository

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Emacs-Guide#31]
## What is needed?
Someone to link all parts of the tutorial to the table of contents in the README.md file

**Comment by rcallaby** [comment]
@alfadelta10010 It is all yours now

**Comment by DanielZhang111** [comment]
can i get assigned to this too?

**Comment by rcallaby** [comment]
@DanielZhang111 No, it has already been assigned. I think there may be some confusion as to the scope of the issue. The scope of the issue only covers the table of contents in the readme.md file. There are other issues which cover different parts of the repository. You're welcome to request to be added to one of those.
