### ISSUE TITLE
Add Images/Screenshots that help explain concepts in Part 4

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Emacs-Guide#63]
### What is needed?

Essentially, just add screenshots or images that help explain the concepts in Part 4 if they are applicable. I am going to try and trust your judgement on this that you know what you are doing.

Please note: Only ask to be assigned this task if you know how to take screenshots and incorporate them into a markdown file. Or at least have the ability to research this on your own.

**Comment by Ethaaan11** [comment]
@rcallaby could i be assigned to this task please?

**Comment by rcallaby** [comment]
@Ethaaan11 It is all yours now.

**Comment by rcallaby** [comment]
@Ethaaan11 Any progress on this?
